name: Auto-Grader
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: write

jobs:
  grade:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install Dependencies
        run: pip install pandas tabulate

      - name: Run Judge
        run: |
          python3 src/evaluator.py 

      - name: Update Leaderboard
        # This line ensures the bot ONLY tries to push when code is merged to main
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "Leaderboard-Bot"
          
          git add leaderboard.md
          git stash
          
          git checkout main || git checkout -b main
          git pull origin main --rebase
          
          git stash pop || echo "No changes to apply"
          
          git add leaderboard.md
          git commit -m "update: leaderboard [skip ci]" || echo "No changes to commit"
          git push origin HEAD:main
